export const FOODS_EXPORT=[
  {key:"white_rice",name:"밥(백미)",kcal:150,unit:"g"},
  {key:"brown_rice",name:"현미밥",kcal:140,unit:"g"},
  {key:"ramen",name:"라면",kcal:500,unit:"g"},
  {key:"jjajang",name:"짜장면",kcal:480,unit:"g"},
  {key:"kimchi_stew",name:"김치찌개",kcal:60,unit:"g"},
  {key:"doenjang_stew",name:"된장찌개",kcal:45,unit:"g"},
  {key:"pork_belly",name:"삼겹살",kcal:330,unit:"g"},
  {key:"fried_chicken",name:"치킨(후라이드)",kcal:250,unit:"g"},
  {key:"sweet_chicken",name:"치킨(양념)",kcal:280,unit:"g"},
  {key:"pizza",name:"피자",kcal:270,unit:"g"},
  {key:"burger",name:"햄버거",kcal:250,unit:"g"},
  {key:"kimbap",name:"김밥",kcal:185,unit:"g"},
  {key:"tteokbokki",name:"떡볶이",kcal:200,unit:"g"},
  {key:"bread",name:"빵(식빵)",kcal:265,unit:"g"},
  {key:"milk",name:"우유",kcal:63,unit:"ml"},
  {key:"cola",name:"콜라",kcal:40,unit:"ml"},
  {key:"beer",name:"맥주",kcal:43,unit:"ml"},
  {key:"soju",name:"소주",kcal:130,unit:"ml"},
  {key:"coffee_americano",name:"커피(아메리카노)",kcal:2,unit:"ml"},
  {key:"coffee_latte",name:"커피(라떼)",kcal:50,unit:"ml"},
  {key:"apple",name:"사과",kcal:52,unit:"g"},
  {key:"banana",name:"바나나",kcal:89,unit:"g"},
  {key:"boiled_egg",name:"계란(삶은)",kcal:155,unit:"g"},
  {key:"sweet_potato",name:"고구마",kcal:110,unit:"g"},
  {key:"salad",name:"샐러드(드레싱 포함)",kcal:80,unit:"g"},
  {key:"triangular_kimbap",name:"삼각김밥",kcal:170,unit:"g"},
  {key:"cup_ramen",name:"컵라면",kcal:450,unit:"g"},
  {key:"jokbal",name:"족발",kcal:210,unit:"g"},
  {key:"bossam",name:"보쌈",kcal:180,unit:"g"},
  {key:"bibimbap",name:"비빔밥",kcal:160,unit:"g"}
];
export const FOODS = FOODS_EXPORT
